### ISSUE TITLE
Section re-ordering confuses `strip`

### ISSUE THREAD

**Issue by staticfloat** [NixOS/patchelf#10]
Running `patchelf` to enlarge my RUNPATH entry causes my section headers to change from this:

```
Section Headers:
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [ 0]                   NULL             0000000000000000  00000000
       0000000000000000  0000000000000000           0     0     0
  [ 1] .interp           PROGBITS         0000000000400238  00000238
       000000000000001c  0000000000000000   A       0     0     1
  [ 2] .note.ABI-tag     NOTE             0000000000400254  00000254
       0000000000000020  0000000000000000   A       0     0     4
  [ 3] .note.gnu.build-i NOTE             0000000000400274  00000274
       0000000000000024  0000000000000000   A       0     0     4
  [ 4] .gnu.hash         GNU_HASH         0000000000400298  00000298
       0000000000000064  0000000000000000   A       5     0     8
  [ 5] .dynsym           DYNSYM           0000000000400300  00000300
       00000000000011b8  0000000000000018   A       6     1     8
  [ 6] .dynstr           STRTAB           00000000004014b8  000014b8
       0000000000000868  0000000000000000   A       0     0     1
...
```

To this:

```
Section Headers:
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [ 0]                   NULL             0000000000000000  00000000
       0000000000000000  0000000000000000           0     0     0
  [ 1] .dynsym           DYNSYM           00000000003ffb00  001ffb00
       00000000000011b8  0000000000000018   A       2     1     8
  [ 2] .dynstr           STRTAB           00000000003ff270  00000270
       0000000000000890  0000000000000000   A       0     0     8
  [ 3] .gnu.hash         GNU_HASH         0000000000400cb8  00001cb8
       0000000000000064  0000000000000000   A       1     0     8
  [ 4] .interp           PROGBITS         0000000000400d20  00001d20
       000000000000001c  0000000000000000   A       0     0     8
  [ 5] .note.ABI-tag     NOTE             0000000000400d40  00001d40
       0000000000000020  0000000000000000   A       0     0     8
  [ 6] .note.gnu.build-i NOTE             0000000000400d60  00001d60
       0000000000000024  0000000000000000   A       0     0     8
...
```

This confuses tools such as `strip` because they use a header offset of 0 as an error code; here's the [relevant function `assign_file_positions_for_non_load_sections` in elf.c](https://github.com/bneumeier/binutils/blob/master/bfd/elf.c#L4816-4817) from binutils.  Running e.g. `gdb --args strip -g my_binary`, and setting a breakpoint at that position shows that we get a valid section, but since its `filepos` is equal to zero, binutils ignores it and continues on, getting confused.  Note that even `readelf` gets a little confused by this, as it doesn't even list the `.dynsym` segment:

```
$ readelf -l my_binary
...
 Section to Segment mapping:
  Segment Sections...
   00     
   01     .interp 
   02     .interp .note.ABI-tag .note.gnu.build-id .gnu.hash .dynsym .dynstr .gnu.version .gnu.version_r .rela.dyn .rela.plt .init .plt .text .fini .rodata .eh_frame_hdr .eh_frame 
   03     .init_array .fini_array .jcr .data.rel.ro .dynamic .got .got.plt .data .bss 
   04     .dynamic 
   05     .note.ABI-tag .note.gnu.build-id 
   06     .eh_frame_hdr 
   07     
   08     .init_array .fini_array .jcr .data.rel.ro .dynamic .got 
$ readelf my_patched_binary
...
 Section to Segment mapping:
  Segment Sections...
   00     
   01     
   02     .dynstr 
   03     .gnu.hash .interp .note.ABI-tag .note.gnu.build-id .gnu.version .gnu.version_r .rela.dyn .rela.plt .init .plt .text .fini .rodata .eh_frame_hdr .eh_frame 
   04     
   05     .interp 
   06     .eh_frame_hdr 
   07     .init_array .fini_array .jcr .data.rel.ro .dynamic .got .got.plt .data .bss 
   08     .init_array .fini_array .jcr .data.rel.ro .dynamic .got 
   09     .dynamic 
```

I theorize that if we keep the `.interp` section at the beginning of the file, we might be able to still use tools such as `strip`, but I don't actually know.  Is there an easy way to permute the order of headers that `patchelf` outputs?  If you can just point me in the direction of how to do this, I can submit a PR.

**Comment by 2sin18** [comment]
Is there any progress?

**Comment by sjackman** [comment]
I'm seeing this error as well, which makes it impossible to run `strip` after `patchelf`.

**Comment by davidedelvento** [comment]
FWIW this problem affects me too, via https://github.com/schmir/bbfreeze

**Comment by mitchblank** [comment]
Yeah, I'm seeing something similar.  On CentOS 7 strip (2.23.52.0.1-30.el7_1.2) I don't get that exact error, but patchelf 0.9 followed by strip does produce a broken binary.

In the post-patchelf'ed binary, DT_STRTAB seems to end up in the first page of the executable, which includes references to things like needed libraries.

```
$ dd bs=4k count=1 if=after-patchelf 2>/dev/null | strings | head
__libc_csu_fini
_start
__tls_get_addr
GLIBC_2.3
ld-linux-x86-64.so.2
[...]
```

but after running strip on it , they're no longer in that position of the file:

```
$ dd bs=4k count=1 if=after-patchelf-and-strip 2>/dev/null | strings | wc -l
0
```

However, when I've been walking through the dynamic linker code in gdb, it seems that in `_dl_check_map_versions` the `strtab` points into this page and is all `\0` bytes, breaking its ability to find the libcs:

```
(gdb) x/40c 0x3ff580
0x3ff580:	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
0x3ff588:	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
0x3ff590:	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
0x3ff598:	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
0x3ff5a0:	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'	0 '\000'
```

I'm still digging a bit, hoping to find at least a workaround.  Unfortunately I need to produce unstripped binaries to hand to our release engineering process where do the final strip before shipping, so right now trying to use patchelf to fix the rpath inside is resulting in binaries that can't be stripped.

**Comment by mitchblank** [comment]
OK, I dug into this more.  The problem doesn't seem specific to the re-ordering, but that the `PT_LOAD` program sections that patchelf set up are...dubious.  Here is some of the information from `readelf -Wl` on my original executable (with a little manual reformatting for clarity.  I'm only including the LOAD segments since that's what controls what the kernel will actually map into our image.

```
  Type  Offset    VirtAddr           PhysAddr           FileSiz   MemSiz    Flg Align
  LOAD  0x0000000 0x0000000000400000 0x0000000000400000 0x1c3faa0 0x1c3faa0 R E 0x1000
  LOAD  0x1c3faa0 0x0000000002040aa0 0x0000000002040aa0 0x000bfc8 0x005b170 RW  0x1000

   02     .interp .note.ABI-tag .note.gnu.build-id .dynsym .dynstr .gnu.hash .gnu.version .gnu.version_r .rela.dyn .rela.plt .init .plt .text .fini .rodata .gcc_except_table .stapsdt.base .eh_frame .eh_frame_hdr
   03     .dynamic .got .got.plt .data .jcr .tm_clone_table .fini_array .init_array .data.rel.ro.local .data.rel.ro .bss
```

The `.dynstr` is one of the many segments in the first LOAD section... so far so unremarkable.

Now after running patchelf 0.9 things get odd:

```
  Type  Offset    VirtAddr           PhysAddr           FileSiz   MemSiz    Flg Align
  LOAD  0x0000000 0x00000000003ff000 0x00000000003ff000 0x0001000 0x0001000 RW  0x1000
  LOAD  0x0001000 0x0000000000400000 0x0000000000400000 0x1c3faa0 0x1c3faa0 R E 0x1000
  LOAD  0x1c40aa0 0x0000000002040aa0 0x0000000002040aa0 0x000bfc8 0x005b170 RW  0x1000

   02     .dynamic
   04     .dynsym .interp .note.ABI-tag .note.gnu.build-id .gnu.hash .gnu.version .gnu.version_r .rela.dyn .rela.plt .init .plt .text .fini .rodata .gcc_except_table .stapsdt.base .eh_frame .eh_frame_hdr
   08     .got .got.plt .data .jcr .tm_clone_table .fini_array .init_array .data.rel.ro.local .data.rel.ro .bss
```

so now there are *three* LOAD segments.  The first `rw-` one covers just one page (just under address 0x400000) and then is immediately followed by a larger `r-x` one.  But if you look at the dynstr section...

```
  [Nr] Name                   Type       Address            Off      Size   ES Flg Lk Inf Al
  [ 2] .dynstr                STRTAB     00000000003ff580   000580   2fc53d 00   A  0   0  8
```

...it starts in the first `PT_LOAD` section and continues onto the second one!  That definitely looks wrong: having a segment cross section boundaries can't really be safe can it?

Anyway, then when we run `strip` on this binary it unsurprisingly doesn't survive.  You still get the three LOAD sections:

```
  Type  Offset    VirtAddr           PhysAddr           FileSiz   MemSiz    Flg Align
  LOAD  0x0000000 0x00000000003ff000 0x00000000003ff000 0x0000580 0x0000580 RW  0x1000
  LOAD  0x0001000 0x0000000000400000 0x0000000000400000 0x1c3faa0 0x1c3faa0 R E 0x1000
  LOAD  0x1c40aa0 0x0000000002040aa0 0x0000000002040aa0 0x000bfc8 0x005b170 RW  0x1000
```

...notice that the `FileSiz`/`MemSiz` has now shrunk and now doesn't cover the whole page.  `strip` has moved the dynstr and now it's no longer covered in the LOAD sections.

```
  [Nr] Name                   Type       Address          Off     Size    ES Flg Lk Inf Al
  [ 3] .dynstr                STRTAB     00000000003ff580 1dff580  2fc53d 00   A  0   0  8
```

...and thus ld-linux.so can no longer find our dependencies.  The will appear to be there if you look at the file with objdump since they're present in the file, but they're no longer in a section of the file that gets  memory mapped in at `execve()` time.

**Comment by Shonallein** [comment]
I'm having a hard time with this issue as well. @mitchblank Did you find a work around the issue since you narrowed it down ? Or do you just don't strip your executable after patchelf ?

**Comment by mitchblank** [comment]
No, I didn't find a workaround.  For now I'm pursuing other options.

**Comment by ogrisel** [comment]
Any idea how to fix this issue? The problem is also affecting binary wheel packages for Python using the manylinux1 specification (`patchelf` is internally used by the `auditwheel` tool to graft third party dynamic libs into those Python packages when necessary).

**Comment by staticfloat** [comment]
I made some progress on this tonight; here are the results of my investigations:

* `strip` on libraries was, (in the test case I added [here](https://github.com/staticfloat/patchelf/blob/7f6fcb43f6db63a6dd53629a894e6a97787104b4/tests/soname-strip.sh)) failing on [this line in `bfd/elf.c`](https://github.com/bminor/binutils-gdb/blob/master/bfd/elf.c#L5350) inside of the function `assign_file_positions_for_load_sections()`.  Essentially, the destination virtual memory address of the section being loaded in was lower than the current file offset, which means it's overlapping the program header table, which `strip()` didn't like.  So, I [added in a fix](https://github.com/staticfloat/patchelf/commit/7f6fcb43f6db63a6dd53629a894e6a97787104b4#diff-ecd3d9ea3a7bedb9da1146861deba89eR683) to relocate sections that were overlapping to the end of the library, and it seems to have worked!  You can try out my branch by checking out the `sf/pr_10` branch on my fork, building the `patchelf` executable and using it in your workflows.

* I'm having trouble reproducing the original error I reported, (namely, errors when running `strip` on executables (not libraries) that have been modified by `patchelf`) if anyone has an executable that causes an error with the latest versions of `patchelf` and `strip` (which is a part of [binutils](https://www.gnu.org/software/binutils/)) I'd like to be brought to its attention so that I can add in a test case for it to `patchelf` and hopefully start chipping away at that one too!

**Comment by ogrisel** [comment]
Thanks @staticfloat, I will try to test your branch in the manylinux1 / Python workflow some times this week (if nobody does it first).

**Comment by sjackman** [comment]
Thanks, Elliot! That's great news.

I see this error message `Not enough room for program headers, try linking with -N` when trying to build GHC (GNU Haskell Compiler) inside of Linuxbrew using a recent binary snapshot of GHC to compile a recent source distribution.
See https://github.com/Linuxbrew/homebrew-core/pull/1378
I'm not sure if it's caused by a library or an executable without looking into it further. I can give more information if you'd like to try to reproduce this error yourself.

**Comment by ogrisel** [comment]
I tried to build a manylinux1 wheel (fixed by your version of patchelf) for the lxml project (that uses external libraries lxml2 and libxslt).

Here is the kind of errors I got prior to using your fix when trying to strip the resulting .so files:

```
$ find envs/teststrip/ -name "*.so*" | xargs strip
BFD: envs/teststrip/lib/python3.6/site-packages/lxml/stQQUQun: Not enough room for program headers, try linking with -N
strip:envs/teststrip/lib/python3.6/site-packages/lxml/stQQUQun[.note.gnu.build-id]: Bad value
BFD: envs/teststrip/lib/python3.6/site-packages/lxml/stQQUQun: Not enough room for program headers, try linking with -N
strip:envs/teststrip/lib/python3.6/site-packages/lxml/stQQUQun: Bad value
BFD: envs/teststrip/lib/python3.6/site-packages/lxml/stutiC3s: Not enough room for program headers, try linking with -N
strip:envs/teststrip/lib/python3.6/site-packages/lxml/stutiC3s[.note.gnu.build-id]: Bad value
BFD: envs/teststrip/lib/python3.6/site-packages/lxml/stutiC3s: Not enough room for program headers, try linking with -N
strip:envs/teststrip/lib/python3.6/site-packages/lxml/stutiC3s: Bad value
BFD: envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stoA4ECy: Not enough room for program headers, try linking with -N
strip:envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stoA4ECy[.note.gnu.build-id]: Bad value
BFD: envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stoA4ECy: Not enough room for program headers, try linking with -N
strip:envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stoA4ECy: Bad value
BFD: envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stuEcLbE: Not enough room for program headers, try linking with -N
strip:envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stuEcLbE[.note.gnu.build-id]: Bad value
BFD: envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stuEcLbE: Not enough room for program headers, try linking with -N
strip:envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stuEcLbE: Bad value
BFD: envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stB5xbLJ: Not enough room for program headers, try linking with -N
strip:envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stB5xbLJ[.gnu.hash]: Bad value
BFD: envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stB5xbLJ: Not enough room for program headers, try linking with -N
strip:envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stB5xbLJ: Bad value
BFD: envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stA69EkP: Not enough room for program headers, try linking with -N
strip:envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stA69EkP[.gnu.hash]: Bad value
BFD: envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stA69EkP: Not enough room for program headers, try linking with -N
strip:envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stA69EkP: Bad value
BFD: envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stzlGcUU: Not enough room for program headers, try linking with -N
strip:envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stzlGcUU[.gnu.hash]: Bad value
BFD: envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stzlGcUU: Not enough room for program headers, try linking with -N
strip:envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stzlGcUU: Bad value
BFD: envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stlI8Nt0: Not enough room for program headers, try linking with -N
strip:envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stlI8Nt0[.note.gnu.build-id]: Bad value
BFD: envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stlI8Nt0: Not enough room for program headers, try linking with -N
strip:envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stlI8Nt0: Bad value
(teststrip) ogrisel@is146148:~$ du -hs envs/teststrip/
46M	envs/teststrip/
```

with your fix I get the following output:

```
(teststrip) ogrisel@is146148:~$ find envs/teststrip/ -name "*.so*" | xargs strip
BFD: envs/teststrip/lib/python3.6/site-packages/lxml/stwFheJb: section .dynamic lma 0x277268 adjusted to 0x2e8228
BFD: envs/teststrip/lib/python3.6/site-packages/lxml/stwFheJb: section .dynstr lma 0x2774a8 adjusted to 0x2e8468
BFD: envs/teststrip/lib/python3.6/site-packages/lxml/st8HVQ4R: section .dynamic lma 0x42a268 adjusted to 0x640228
BFD: envs/teststrip/lib/python3.6/site-packages/lxml/st8HVQ4R: section .dynstr lma 0x42a4a8 adjusted to 0x640468
BFD: envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stxmfwsy: section .dynstr lma 0x21c2a0 adjusted to 0x234260
BFD: envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stysfiQe: section .dynstr lma 0x3711c0 adjusted to 0x4e1180
BFD: envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stzaYReV: section .dynstr lma 0x274188 adjusted to 0x2e8148
BFD: envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stybfEDB: section .dynstr lma 0x214150 adjusted to 0x228110
BFD: envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stybfEDB: section .gnu.hash lma 0x2145e8 adjusted to 0x2285a3
BFD: envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stybfEDB: section `.gnu.hash' can't be allocated in segment 5
LOAD: .dynstr .gnu.hash
BFD: envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stjXKv2h: section .dynstr lma 0x203150 adjusted to 0x206110
BFD: envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stjXKv2h: section .gnu.hash lma 0x2032c0 adjusted to 0x20627d
BFD: envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stjXKv2h: section `.gnu.hash' can't be allocated in segment 5
LOAD: .dynstr .gnu.hash
BFD: envs/teststrip/lib/python3.6/site-packages/lxml/.libs/stkLHqrY: section .dynstr lma 0x2451f8 adjusted to 0x2861b8
(teststrip) ogrisel@is146148:~$ du -hs envs/teststrip/
30M	envs/teststrip/
```

the `section .gnu.hash can't be allocated in segment 5` is suspicious but at least we no longer get the originally reported `Not enough room for program headers` error message and the resulting stripped files are indeed smaller.

I can put the resulting binaries (after patchelf but before strip) online if that helps.

**Comment by staticfloat** [comment]
If I could get the original `.so` files (before `patchelf`, and then the `patchelf` command that you're running on them so I can see how the binary is effected by `patchelf`) that would be great.

**Comment by staticfloat** [comment]
Oh, also, if you're using a docker image to do your development inside of, I'd like to use that as well, as there can be a lot of different pieces in this puzzle (version of binutils, etc..) and I'd like to eliminate as many variables as possible.

**Comment by ogrisel** [comment]
The docker image is `quay.io/pypa/manylinux1_x86_64`. A previous version of patchelf (without your fix) has been installed in `/usr/local/bin`. Here are the build scripts and Dockerfile for that image:

https://github.com/pypa/manylinux

Today I don't have access on the computer I used yesterday. Let me generate the binaries again.

**Comment by ogrisel** [comment]
Here are the precise `patchelf` commands I executed:

```
Repairing lxml-3.7.2-cp36-cp36m-linux_x86_64.whl
Grafting: /usr/local/lib/libexslt.so.0.8.17 -> lxml/.libs/libexslt-ffbaa1db.so.0.8.17
Setting RPATH: lxml/.libs/libexslt-ffbaa1db.so.0.8.17 to "$ORIGIN/."
patchelf --replace-needed libexslt.so.0 libexslt-ffbaa1db.so.0.8.17 lxml/etree.cpython-36m-x86_64-linux-gnu.so
Grafting: /usr/local/lib/libxml2.so.2.9.3 -> lxml/.libs/libxml2-8d315a96.so.2.9.3
patchelf --replace-needed libxml2.so.2 libxml2-8d315a96.so.2.9.3 lxml/etree.cpython-36m-x86_64-linux-gnu.so
Grafting: /usr/local/lib/libxslt.so.1.1.29 -> lxml/.libs/libxslt-655d9087.so.1.1.29
Setting RPATH: lxml/.libs/libxslt-655d9087.so.1.1.29 to "$ORIGIN/."
patchelf --replace-needed libxslt.so.1 libxslt-655d9087.so.1.1.29 lxml/etree.cpython-36m-x86_64-linux-gnu.so
Grafting: /lib64/libz.so.1.2.3 -> lxml/.libs/libz-a147dcb0.so.1.2.3
patchelf --replace-needed libz.so.1 libz-a147dcb0.so.1.2.3 lxml/etree.cpython-36m-x86_64-linux-gnu.so
Setting RPATH: lxml/etree.cpython-36m-x86_64-linux-gnu.so to "$ORIGIN/.libs"
patchelf --replace-needed libexslt.so.0 libexslt-ffbaa1db.so.0.8.17 lxml/objectify.cpython-36m-x86_64-linux-gnu.so
patchelf --replace-needed libxml2.so.2 libxml2-8d315a96.so.2.9.3 lxml/objectify.cpython-36m-x86_64-linux-gnu.so
patchelf --replace-needed libxslt.so.1 libxslt-655d9087.so.1.1.29 lxml/objectify.cpython-36m-x86_64-linux-gnu.so
patchelf --replace-needed libz.so.1 libz-a147dcb0.so.1.2.3 lxml/objectify.cpython-36m-x86_64-linux-gnu.so
Setting RPATH: lxml/objectify.cpython-36m-x86_64-linux-gnu.so to "$ORIGIN/.libs"
patchelf --replace-needed libxslt.so.1 libxslt-655d9087.so.1.1.29 lxml/.libs/libexslt-ffbaa1db.so.0.8.17
patchelf --replace-needed libxml2.so.2 libxml2-8d315a96.so.2.9.3 lxml/.libs/libexslt-ffbaa1db.so.0.8.17
patchelf --replace-needed libxml2.so.2 libxml2-8d315a96.so.2.9.3 lxml/.libs/libxslt-655d9087.so.1.1.29
```

The original binaries can be found in this `.whl` file (you can just unzip it to get all the `.so` files in it:

https://dl.dropboxusercontent.com/u/5743203/tmp/lxml-3.7.2-cp36-cp36m-linux_x86_64.whl

Here are the original system libs (from /usr/local/lib) that are being grafted into the package using patchelf:

https://dl.dropboxusercontent.com/u/5743203/tmp/libexslt.so.0
https://dl.dropboxusercontent.com/u/5743203/tmp/libxml2.so.2
https://dl.dropboxusercontent.com/u/5743203/tmp/libxslt.so.1

Here is the resulting package (with your fix):

https://dl.dropboxusercontent.com/u/5743203/tmp/after-patchelf-7f6fcb43-lxml-3.7.2-cp36-cp36m-manylinux1_x86_64.whl

and here is the copy of the same results without your fix in patchelf:

https://dl.dropboxusercontent.com/u/5743203/tmp/before-patchelf-7f6fcb43-lxml-3.7.2-cp36-cp36m-manylinux1_x86_64.whl

**Comment by staticfloat** [comment]
Thanks @ogrisel, that was really helpful!

When `patchelf` relocates the program header table to the end of the file, everything gets wonked out.  (That is the technical term)  It appears that `libbfd` has [very strong opinions](https://github.com/bminor/binutils-gdb/blob/6624f3a142811450fab7eed1f406c4a030c3c9be/bfd/elf.c#L5367-L5374) about the allowable segment offsets in a segment that contains the program headers.  That is to say, it enforces that they must be at the beginning of the file.  This is very strange to me, but I'm willing to roll with it.  I cannot say I understand `libbfd` well enough to determine whether this is a bug, but I can say that simply telling `patchelf` to not put the program header table at the end of the file and to keep it where it is seems to have worked out when put in conjunction with my earlier changes.  That is to say, the test suite passes, and `strip` doesn't crap out when processing `libexslt.so` as provided by @ogrisel.

I'm testing this out using [this docker repo](https://github.com/staticfloat/manylinux_patchelf_debugging), the scripts in there will download everything you need to play around with this stuff, in case for some reason you want to.  I don't have an easy way to test that the libraries that `strip` is outputting actually work, so be sure to test these really thoroughly!  The test suite of `patchelf` is pretty light.

**Comment by ogrisel** [comment]
> I cannot say I understand libbfd well enough to determine whether this is a bug

I think it's worth asking the `libbfd` maintainers.

**Comment by ogrisel** [comment]
>  I don't have an easy way to test that the libraries that strip is outputting actually work, so be sure to test these really thoroughly! The test suite of patchelf is pretty light.

@matthew-brett do you think you could adapt your manylinux1 testing infrastructure to ensure that this patchelf fix does not introduce a regression on all the manylinux1 packages you tested in the past?

**Comment by matthew-brett** [comment]
Olivier - just to clarify - you want me to try building and testing a few wheels with the patchelf fix you refer to here : https://github.com/pypa/manylinux/issues/78#issuecomment-271310178 ?

**Comment by ogrisel** [comment]
Yes I was thinking about leveraging https://github.com/matthew-brett/manylinux-builds to check that the branch https://github.com/staticfloat/patchelf/tree/sf/pr_10 does not cause a regression on a variety of packages at once. However know I realize that the `manylinux-builds` does not run the tests for those projects (contrary to the individual multibuild-based CI configs of those projects).

I guess some manual testing is required then.

**Comment by matthew-brett** [comment]
Hmm - I guess we could modify the upload container for the manylinux-builds .travis.yml, and then run manylinux-testing, reading from that new container...

**Comment by darealshinji** [comment]
Is this issue fixed by https://github.com/NixOS/patchelf/pull/117 ?

**Comment by JonathonReinhart** [comment]
As @darealshinji mentioned, I believe this is fixed by #117. Would a maintainer mind closing it if this is indeed true?

Also, as we've seen, there are a lot of tools depending on this new, correct behavior. Are there plans to cut a new release of `patchelf` anytime soon? Thanks.

**Comment by sjackman** [comment]
Is a new release of `patchelf` upcoming?

**Comment by yegortimoshenko** [comment]
This is not fixed. With the latest version, even with #127 applied, when I create a binary with rpath larger than it was before (e.g. via `patchelf --set-rpath $(patchelf --print-rpath $f):foo $f`) and then strip it, the binary gets corrupted.

**Comment by sjackman** [comment]
Cool work around:

> When patchelf has to grow rpath beyond original capacity, it sets dontStrip, to work around NixOS/patchelf#10.

See https://github.com/yegortimoshenko/nixpkgs/commit/aebc2b8911bacf84d0e3db62dafc4db4fb4863fb

**Comment by sjackman** [comment]
@staticfloat Has this issue been resolved? Is there a related PR that fixes this issue?

**Comment by staticfloat** [comment]
It looks to me like https://github.com/NixOS/patchelf/pull/117 fixed this.

**Comment by sjackman** [comment]
Excellent! Are there plans for a new stable release of `patchelf` that includes this fix?

**Comment by staticfloat** [comment]
It doesn't look like there's been a release for quite a while; we use `patchelf` as part of the fundamental infrastructure of our [`BinaryBuilder.jl`](https://github.com/JuliaPackaging/BinaryBuilder.jl) system to build binary dependencies for the Julia language project.   I just recently built redistributable binaries of the latest `patchelf` for all the major operating systems, hosted [here](https://github.com/staticfloat/PatchelfBuilder/releases/tag/v2018.5.9) if that's helpful to anyone looking for an easy way to get at them.  (Just download and extract the tarball)
