### ISSUE TITLE
isExecutable check for PHDR placement adjustment isn't reliable

### ISSUE THREAD

**Issue by rcombs** [NixOS/patchelf#165]
See https://github.com/NixOS/patchelf/blob/60662393ba843d68e17f4d87a13bccda58b4b2c0/src/patchelf.cc#L745

This check is insufficient, as it only handles cases where the file has a PT_INTERP header, which means it won't run on static executables. Most static executables don't need to read AT_PHDR, but some do; e.g. static PIE executables.

This could alternately be handled by enforcing that PHDRs are always in the first page, which would also fix #153.

**Comment by rcombs** [comment]
Actually, it looks like the #153 is already fixed in 63d0db9a71fbcd0ab6bbcdeff66c71d5ba262618, so the impact of removing the `isExecutable` check altogether should be fairly minor at this point (barring other issues like #164).

**Comment by domenkozar** [comment]
Since https://nixos.org/releases/patchelf/patchelf-0.10/ is out, this is fixed?

**Comment by rcombs** [comment]
The issue persists in master. I'll be sending a PR with a few relevant changes shortly.

**Comment by ararslan** [comment]
> Actually, it looks like the #153 is already fixed in 63d0db9

Is it? I opened #153 a year _after_ that commit. :thinking:

**Comment by domenkozar** [comment]
The PR is at https://github.com/NixOS/patchelf/pull/166 but it would be great if someone can reproduce this on master (and ideally attach a binary to this issue and describe how to reproduce).
