### ISSUE TITLE
_arguments:463: command not found: dynamic

### ISSUE THREAD

**Issue by zhefox** [NixOS/patchelf#549]
**Describe the bug**

➜  / patchelf --set-interpreter /root/tools/glibc_arguments:463: command not found: dynamic27.so ./chatting
_arguments:463: command not found: dynamic
_arguments:463: command not found: dynamic
patchelf                   /root/tools/glibc

**Steps To Reproduce**

install zsh and history plugin then tab to complement path

**`patchelf --version` output**

➜  / patchelf --version
patchelf 0.18.0

**Comment by zhefox** [comment]
plugins=(
        git
        zsh-autosuggestions
        zsh-syntax-highlighting
)

**Comment by RocketMaDev** [comment]
Check out my pr above :)
I fixed the problem you mentioned and enhanced it. Please check your fpath (check out by `echo $fpath`), download `_patchelf` in my fork, and replace your existed `_patchelf`, which is in one of the fpaths. Restart your zsh, and the correct completion will take effect.

**Comment by zhefox** [comment]
thanks,i will try

**Comment by zhefox** [comment]
I confirm you fixed it and I will close this bug issue

**Comment by RocketMaDev** [comment]
@zhefox I pushed a new commit, now files like `./chatting` can get dep completion. Plz download my latest edition to get a better experience.

**Comment by zhefox** [comment]
> @zhefox I pushed a new commit, now files like `./chatting` can get dep completion. Plz download my latest edition to get a better experience.

Thank u, I have updated it.

**Comment by LittFlower** [comment]
> Check out my pr above :) I fixed the problem you mentioned and enhanced it. Please check your fpath (check out by `echo $fpath`), download `_patchelf` in my fork, and replace your existed `_patchelf`, which is in one of the fpaths. Restart your zsh, and the correct completion will take effect.

Sorry, I have tried the latest version of commit (which I compiled myself), but I still have problems with the completion in zsh. What should I do?

**Comment by RocketMaDev** [comment]
@LittFlower please confirm that zsh run the right completion script.

**Comment by LittFlower** [comment]
Ohhhh.... This is my negligence, and I apologize for it.... I'm sorry for wasting your time and thank you very much for your reminder!
